### Table of Contents
To return to the table of contents, click on the number at any major section heading.

[1. Project Title](#1.-Project-Title)

[2. Team members](#2.-Team-members)

[3. Question(s) you addressed, why it is important](#3.-Question(s)-you-addressed,-why-it-is-important)

[4. Background and literature](#4.-Background-and-literature)

[5. Python packages you used and why](#5.-Python-packages-you-used-and-why)

[6. Data sources](#6.-Data-sources)

[7. Data cleaning you have done](#7.-Data-cleaning-you-have-done)

[8. Descriptive statistics for the data](#8.-Descriptive-statistics-for-the-data)

[9. Analysis](#9.-Analysis)

[10. Summary of products and results](#10.-Summary-of-products-and-results)

[11. Discussion](#11.-Discussion)

[12. Conclusions and future work](#12.-Conclusions-and-future-work)

### [1.](#Table-of-Contents) Project Title

Exploring the Impact of Computer Ownership on Unemployment in San Diego, CA

### [2.](#Table-of-Contents) Team members

By: Michael Garcia-Perez (A16366187) & Haoyu Fu (A16633278)

### [3.](#Table-of-Contents) Question(s) you addressed, why it is important

We aim to delve deeper into the relationship between computer ownership and unemployment in San Diego, California, while also considering additional factors if time allows. The primary audience for our research includes political officials and policymakers in San Diego. This focus is particularly relevant because if a significant relationship exists between computer ownership and unemployment, it suggests that enhancing citizens' access to such equipment could contribute to boosting the employment rate.

San Diego, CA, is a thriving city; however, homelessness has become a growing concern among residents, evident in headlines such as "Downtown San Diego homeless population reaches record high for the sixth month in a row" (Warth, LA Times). Homelessness stems from various causes, including a lack of affordable housing, poverty, and unemployment. Despite common misconceptions associating homelessness with mental health issues, a comprehensive survey revealed that poverty is the primary culprit (The Coronado Times). The cost of living in San Diego is a driving factor, but so is "inadequate employment," such as the "inability to find gainful employment..." (The Coronado Times). Hence, homelessness can be linked to unemployment, prompting us to explore additional relationships, including those involving computer ownership.

We believe that computer ownership could significantly impact unemployment in San Diego. Initially unaware of the issue's significance, we were surprised to discover a dataset on computer ownership before starting our research. Our analysis also aims to uncover information related to the number of broadband providers per San Diego census tract, Federal Broadband Threshold compliance, income, ethnic populations, and more, if time permits, utilizing broadband data from SANDAG and visualizing through San Diego census tracts.

Our expectations include identifying a strong relationship between computer ownership and unemployment rates in different San Diego census tracts. We anticipate that individuals without access to computers may face challenges in job applications, potentially leading to higher unemployment rates. Ultimately, we hope our findings offer a new perspective on the factors influencing unemployment in certain San Diego areas and provide insights for policymakers on utilizing tax money to fund initiatives promoting increased computer ownership, should it prove to positively impact the employment rate.

### [4.](#Table-of-Contents) Background and literature

1. https://www.utwente.nl/en/bms/vandijk/publications/digital_divide_impact_access.pdf
2. https://www.sciencedirect.com/science/article/pii/S0040162521007903?casa_token=8X2wFMUI1bsAAAAA:bgo7kmgL2LXDxj0fmjMEv0ZoSaLLMTQuY3WEPV1n9nHhRgdTpY7_0tUvDW77bmxlYUH9CtIP1w
3. https://files.eric.ed.gov/fulltext/ED463391.pdf
4. https://www.sciencedirect.com/science/article/pii/S026427512031252X?casa_token=_jvi54cy2FcAAAAA:Cmou9AI7qMpBBHCH1bAjAVWWQFe5QBN-sZGBU9tvg8mD8uGtYDfPflMQ6ILBVFjODOT8IW-PFA

These references play a crucial role in providing essential background literature necessary for comprehending our topic, which involves investigating the influence of computer ownership on unemployment in San Diego. The articles explore subjects such as the digital divide and broadband access. The digital divide represents an inequality where more privileged individuals have access to digital resources like the internet, along with the skills and hardware necessary for utilizing these resources, such as laptops or phones. This reference has been instrumental in refining our focus, especially since we concentrate on computer ownership and its impact on unemployment.

As highlighted in these articles, the digital divide significantly affects employment. Without computers or internet access, the process of applying for jobs or acquiring new skills becomes exceedingly challenging. Employment relies heavily on these resources, as job seekers need to submit applications, connect with recruiters, participate in interviews, respond to crucial emails, learn about job positions, and more. While libraries can help mitigate the impact of the digital divide, managing these tasks is still more challenging compared to having access to a computer and reliable internet at home. Finding a job is inherently challenging due to the competitive job market and economy, but the digital divide has evidently exacerbated these difficulties, as outlined in these articles.

Another pivotal aspect from these articles that significantly influences our research is understanding broadband access. Broadband, as described in the aforementioned articles, determines your access to reliable internet. To achieve high-speed internet connections, your broadband access must facilitate the transmission of large amounts of data at fast speeds, ultimately affecting your ability to use your laptop for job searching and employment-related activities. We assert that computer ownership and broadband access are interconnected, as a computer without internet access is not useful for employment-seeking purposes. Furthermore, different census tracts in San Diego exhibit varying qualities and speeds of broadband internet, leading us to narrow our focus on a specific hypothesis. We aim to explore how these variations impact different tracts in San Diego and their effects on unemployment.

### [5.](#Table-of-Contents) Python packages you used and why

Will do once we finish implementation...

In [1]:
# Importing necessary packages
import numpy as np
import pandas as pd
import geopandas as gpd
import matplotlib.pyplot as plt
from shapely import wkt

import warnings
warnings.filterwarnings("ignore")

import arcgis
from arcgis.gis import GIS

from sklearn.preprocessing import *
from sklearn.linear_model import *
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split

In [2]:
gis = GIS(username='dsc170wi24_9', password='GPAAAAAA100')

### [6.](#Table-of-Contents) Data sources

1.  https://opendata.sandag.org/Sustainable-Development-Goals/SDG-Indicator-5-b-1-Data-Computer-Ownership/tsaq-axm2/abo

    - This URL provides data regarding computer ownership in San Diego. Specifically, the data includes information on the number of households with one or more types of computing devices, such as desktops, laptops, smartphones, tablets, or other portable wireless computers, and other computer types. There are no concerns related to data quality or constraints. The geographic granularity of this data is census tracts, making it ideal for use with the other data source we have identified. Our choice of sources has evolved since the proposal phase, as we considered whether to join/merge data by census tracts instead of zip codes. We decided that analyzing census tracts would yield more comprehensive results, given the greater number of census tracts in San Diego compared to zip codes. Although we cannot use the zip code data, there is still ample information available for analysis from this URL.
    
    
2. https://opendata.sandag.org/stories/s/Digital-Divide-2-0-Broadband-Access-and-More/9vde-3c89/

    - This URL contains data about broadband providers per census block code, including bandwidth performance/accessibility and geographic information. Specifically, this URL provides three different dataframes that we can utilize in our analysis. We aim to convert the census block code to census tracts and use the data accordingly. While there might be a need for significant data cleaning, there are no concerns related to data quality or constraints. Once again, our choices of sources have evolved, and we have decided to focus solely on data associated with census tracts instead of zip codes.
    
    
3. We will be getting information about unemployment via Geoenrichment from ArcGIS

In [3]:
# Reading all CSV files into GeoDataFrames
computer_ownership = gpd.read_file('SDG_Indicator_5.b.1_Data_-_Computer_Ownership_20240226.csv') # Yes census tracts
    
broadband2 = gpd.read_file('Digital_Divide_-_Broadband_Providers_Meeting_Federal_Threshold_20240307.csv') # Yes by census block
broadband3 = gpd.read_file('Digital_Divide_-_Fixed_Broadband_Meets_Federal_Threshold_20240307.csv') # Yes by census block
broadband6 = gpd.read_file('Digital_Divide_2.0_Scoring_Data_20240307.csv') # Yes by tract and geoid

In [4]:
# Getting unemployment data from ArcGIS contents
unempl_content = gis.content.get('a93ad1fcf4a64580b7dbfa3758252ef0')
unempl_tract = unempl_content.layers[2].query().sdf
unempl_county = unempl_content.layers[1].query().sdf

In [5]:
# Getting internet data from ArcGIS contents
internet_content = gis.content.get('4f43b3bb1e274795b14e5da42dea95d5')
internet_county = internet_content.layers[1].query().sdf

### [7.](#Table-of-Contents) Data cleaning you have done

In [6]:
unempl_SD = unempl_tract[unempl_tract['County'] == 'San Diego County']
unempl_SD['unemplymt'] = unempl_SD['B23025_calc_pctUnempE']
unempl_SD = unempl_SD[['NAME','State','County','unemplymt','GEOID','SHAPE']]
unempl_SD_content = gis.content.import_data(unempl_SD)
unempl_SD = unempl_SD_content.layers[0].query().sdf

In [7]:
# remove unnecessary data from Computer Ownership
computer_pd = pd.read_csv('SDG_Indicator_5.b.1_Data_-_Computer_Ownership_20240226.csv')
computer_pd = computer_pd[computer_pd['Geography Type']=='Tract']
computer_pd = computer_pd.dropna(subset=['Geometry'])
computer_pd = computer_pd.rename(columns={'Geometry':'geometry'})
# convert data to SDF
computer_pd['geometry'] = computer_pd['geometry'].apply(wkt.loads)
# computer_pd['geometry'] = computer_pd['geometry'].apply(lambda x: x.centroid)
# computer_pd['centroid'] = computer_pd['geometry'].apply(lambda x: x.centroid)
computer_gdf = gpd.GeoDataFrame(computer_pd).set_crs('epsg:4326').to_crs('epsg:3857')
computer_SD = pd.DataFrame.spatial.from_geodataframe(computer_gdf)
computer_content = gis.content.import_data(computer_SD)
computer_SD = computer_content.layers[0].query().sdf
# computer_SD = computer_SD[['Geography Name','Households','Percent','GEOID','SHAPE']]

In [10]:
# employment_centers = employment_centers.drop(columns=['geometry'])
# computer_ownership = computer_ownership.drop(columns=['geometry'])
# employee_resident_survey = employee_resident_survey.drop(columns=['geometry'])
# unemployment = unemployment.drop(columns=['geometry'])
# business_tax_certificates = business_tax_certificates.drop(columns=['geometry'])

### [8.](#Table-of-Contents) Descriptive statistics for the data

Percentage of households owning a computer in the census tract

In [11]:
computer_SD['Percent_'].describe()

count       736.0
mean     0.959647
std      0.106723
min           0.0
25%           0.9
50%           1.0
75%           1.0
max           1.0
Name: Percent_, dtype: Float64

In [12]:
# notice that there are a few census tracts with 0 computer owner
computer_SD['Percent_'].value_counts()

1.0    516
0.9    200
0.8     12
0.0      7
0.7      1
Name: Percent_, dtype: Int64

In [13]:
# They are the tracts with no households!
computer_SD[computer_SD['Percent_']==0]['Households']
# Therefore we start from 70% when drawing computer ownerships

90     0.0
115    0.0
124    0.0
125    0.0
268    0.0
269    0.0
280    0.0
Name: Households, dtype: Float64

Unemployment Rate in the census tract

In [14]:
unempl_SD['unemplymt'].describe()

count       736.0
mean     6.255842
std      3.900695
min           0.0
25%           3.5
50%           5.6
75%           8.2
max          31.6
Name: unemplymt, dtype: Float64

### [9.](#Table-of-Contents) Analysis

In [168]:
# create a base map
map_comp_unempl = gis.map('San Diego, CA')

In [169]:
# drawing computer ownership
computer_SD.spatial.plot(
    map_widget=map_comp_unempl,
    renderer_type='c',
    col='Percent_',
    class_count=10,
    cmap='Blues',
    line_width=1)

# drawing unemployment
map_comp_unempl.add_layer(unempl_SD_content.layers[0], 
                    {"renderer":"ClassedSizeRenderer",
                    "field_name":"unemplymt",
                    "opacity":0.75})

map_comp_unempl.legend = True
map_comp_unempl

MapView(layout=Layout(height='400px', width='100%'), legend=True)

In [30]:
# create a base map
map_itnt_unempl = gis.map('USA')

In [ ]:
# drawing computer ownership
internet_county.spatial.plot(
    map_widget=map_itnt_unempl,
    renderer_type='c',
    col='B28002_calc_pctNoIntE',
#     class_count=5,
    cmap='Blues',
    line_width=1)

# drawing unemployment
map_itnt_unempl.add_layer(unempl_county.layers[0], 
                    {"renderer":"ClassedSizeRenderer",
                    "field_name":"B23025_calc_pctUnempE",
                    "opacity":0.75})

map_itnt_unempl.legend = True
map_itnt_unempl

### [10.](#Table-of-Contents) Summary of products and results

Computer ownership(tract) vs unemployment

In [189]:
# unify the GEOID for dataset joining
join_left = computer_SD[['GEOID','Percent_']]
join_left['GEOID'] = join_left['GEOID'].apply(lambda x: x[-10:]).astype(int)
join_right = unempl_SD[['GEOID','unemplymt']]
join_right['GEOID'] = join_right['GEOID'].astype(int)

# join the two sides
join_left = join_left.set_index('GEOID')
join_right = join_right.set_index('GEOID')
joined_df = join_left.join(join_right).reset_index()

In [200]:
# assign dependent variable X and independent variable y
X = joined_df[['Percent_']]
y = joined_df[['unemplymt']]
# splitting the dataset into Train and Test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
# create the model and fit
reg = LinearRegression()
reg.fit(X_train, y_train)
y_pred = reg.predict(X_test)

In [201]:
reg.predict(X_test)[:10], y_test[:10]

(array([[6.24051559],
        [6.10574596],
        [6.24051559],
        [6.24051559],
        [6.10574596],
        [6.10574596],
        [6.24051559],
        [6.10574596],
        [6.10574596],
        [6.10574596]]),
      unemplymt
 669        1.8
 33         6.7
 549        5.6
 199        3.2
 264        0.7
 583        2.7
 39         3.9
 554        3.3
 585        4.5
 609        5.7)

In [202]:
mean_squared_error(y_pred, y_test)

17.415821053770813

In [215]:
reg.fit(X, y)
reg.coef_

array([[0.34504165]])

Internet access vs unemployment (county)

In [27]:
# assign dependent variable X and independent variable y
X = internet_county[['B28002_calc_pctNoIntE']]
y = unempl_county[['B23025_calc_pctUnempE']]
# splitting the dataset into Train and Test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
# create the model and fit
reg = LinearRegression()
reg.fit(X_train, y_train)
y_pred = reg.predict(X_test)

In [28]:
reg.predict(X_test)[:10], y_test[:10]

(array([[5.31993941],
        [5.91887394],
        [4.73461703],
        [4.70739273],
        [4.28541613],
        [5.55134593],
        [4.21735539],
        [3.80899093],
        [4.73461703],
        [4.78906562]]),
       B23025_calc_pctUnempE
 299                     7.3
 501                     7.2
 631                     5.2
 2098                    4.1
 1377                    4.4
 1709                    1.3
 564                     2.8
 1323                    3.7
 3060                    3.4
 438                     2.4)

In [29]:
reg.fit(X, y)
reg.coef_

array([[0.13851427]])

### [11.](#Table-of-Contents) Discussion 

### [12.](#Table-of-Contents) Conclusions and future work

##### Citations 
- https://www.latimes.com/california/story/2023-02-07/downtown-homeless-population-reaches-another-high
- https://coronadotimes.com/news/2023/08/29/is-addiction-driving-the-homeless-epidemic-in-san-diego-2/#:~:text=Lack%20of%20Income&text=This%20report%20showed%20that%20six,desperately%20to%20make%20ends%20meet.